export const ADD_POINT = "ADD_POINT";
export const ADD_POINT_SERVER_ERROR = "ADD_POINT_SERVER_ERROR";
export const ADD_POINT_SUCCESS = "ADD_POINT_SUCCESS";
export const FETCH_POINTS = "FETCH_POINTS";
export const FETCH_POINTS_SERVER_ERROR = "FETCH_POINTS_SERVER_ERROR";
export const FETCH_POINTS_SUCCESS = "FETCH_POINTS_SUCCESS";
export const SERVER_ERROR = "SERVER_ERROR";
export const NO_SERVER_ERROR = "NO_SERVER_ERROR";