export enum AppState {
    NO_STATE = 0,
    FETCH_POINTS = 1,
    FETCH_POINTS_SERVER_ERROR = 2,
    FETCH_POINTS_SUCCESS = 3,
    ADD_POINT = 4,
    ADD_POINT_SERVER_ERROR = 5,
    ADD_POINT_SUCCESS = 6
}